name: BUILD

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:

env:
  AWS_REGISTRY: 339570402237.dkr.ecr.eu-west-1.amazonaws.com
  AWS_SERVER_REPOSITORY: company/orbis/django
  AWS_CLIENT_REPOSITORY: company/orbis/client

jobs:
  context-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: List individual context parts
        id: github_context_parts
        run: |
          echo "ACTION PATH ${{ github.action_path }}"
          echo "ACTION REF ${{ github.action_ref }}"
          echo "REF NAME ${{ github.ref_name }}"
          echo "REF TYPE ${{ github.ref_type }}"
          echo "WORKFLOW ${{ github.workflow }}"
          echo "REF ${{ github.ref }}"
      # - name: Dump job context
      #   run: echo '${{ toJSON(job) }}'
      # - name: Dump steps context
      #   run: echo '${{ toJSON(steps) }}'
      # - name: Dump runner context
      #   run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'
